=== Castellers/XML1/05.01. Validación XML - DTD II/Ejercicio_3/vuelos.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Sergio Pedraza Crespo
Curso: ASIR
Fecha: 3/04/2025
Ejercicio: 05.02. ValidaciÃ³n XML - DTD II Ejercicio 3
-->
<!ELEMENT panel_vuelos (nombre_aeropuerto, fecha, vuelo+)>
<!ELEMENT nombre_aeropuerto (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

<!ELEMENT vuelo (diario?, origen, destino, hora_salida, hora_llegada)>
<!ATTLIST vuelo
  codigo ID #REQUIRED
  estado (C|E|R) "E">

<!ELEMENT diario EMPTY>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>

=== Castellers/XML1/05.01. Validación XML - DTD II/Ejercicio_3/vuelos_jfk.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Sergio Pedraza Crespo
Curso: ASIR
Fecha: 3/04/2025
Ejercicio: 05.02. ValidaciÃ³n XML - DTD II Ejercicio 2
-->
<!DOCTYPE panel_vuelos SYSTEM "vuelos.dtd">
<panel_vuelos>
  <nombre_aeropuerto>JFK</nombre_aeropuerto>
  <fecha>20/12/2013</fecha>
  
  <vuelo codigo="V22" estado="R">
    <diario/>
    <origen>New York</origen>
    <destino>Chicago</destino>
    <hora_salida>9:30</hora_salida>
    <hora_llegada>11:30</hora_llegada>
  </vuelo>
  
  <vuelo codigo="V23" estado="C">
    <origen>New York</origen>
    <destino>Miami</destino>
    <hora_salida>10:15</hora_salida>
    <hora_llegada>11:15</hora_llegada>
  </vuelo>
</panel_vuelos>
