<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marcadores [
    <!ELEMENT marcadores (marcador*)>    <!-- * para mÃºltiples marcadores -->
    <!ELEMENT marcador (nombre, url)> 
    <!ELEMENT nombre (#PCDATA)> 
    <!ELEMENT url (#PCDATA)> 
]>

<marcadores>
    <marcador>
        <nombre>W3C</nombre>             <!-- Corregido de M3C a W3C -->
        <url>http://www.w3.org</url>
    </marcador>
    <marcador>
        <nombre>Web Hypertext Application Technology Working Group (WHATWG)</nombre>  <!-- Corregido WHATING -->
        <url>http://www.whatwg.org</url>
    </marcador>
</marcadores>