<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuertos [
    <!ELEMENT aeropuertos (aeropuerto*)>
    <!ELEMENT aeropuerto (nombre, cerrado?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT cerrado EMPTY>
]>

<aeropuertos>
    <aeropuerto>
        <nombre>Berlin Sch√∂nefeld (SFX)</nombre>
        <cerrado/>
    </aeropuerto>
    <aeropuerto>
        <nombre>Berlin Tempelhof (THF)</nombre>
        <cerrado/>
    </aeropuerto>
</aeropuertos>