=== Castellers/XML1/05.01 Validación XML - DTD III/cuentos.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Sergio Pedraza Crespo
Curso: ASIR
Fecha: 3/04/2025
Ejercicio: 05.03. Validación XML - DTD III Ejercicio 1
-->
<!ELEMENT cuento (personajes+, trama, etiqueta*)>
<!ATTLIST cuento
  cod CDATA #REQUIRED
  titulo CDATA #REQUIRED
  genero (infantil|fantasía|terror) #IMPLIED>

<!ELEMENT personajes (personaje+)>
<!ELEMENT personaje (nombre, genero, descripcion?, (descripcion_fisica|imagen|url)?)>
<!ATTLIST personaje
  id ID #REQUIRED
  tipo (principal|secundario|antagonista) "principal">

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT descripcion_fisica (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT url (#PCDATA)>

<!ELEMENT trama (#PCDATA)>
<!ELEMENT etiqueta EMPTY>
<!ATTLIST etiqueta
  nombre CDATA #REQUIRED>

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio
  moneda CDATA "eur">

=== Castellers/XML1/05.01 Validación XML - DTD III/susurro_armario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Sergio Pedraza Crespo
Curso: ASIR
Fecha: 3/04/2025
Ejercicio: 05.02. Validación XML - DTD III Ejercicio 1
-->
<!DOCTYPE cuento SYSTEM "cuentos.dtd">
<cuento cod="T45" titulo="El Susurro del Armario" genero="terror">
  <personajes>
    <personaje id="P1" tipo="principal">
      <nombre>Daniel</nombre>
      <genero>M</genero>
      <descripcion>Un niño de 8 años que escucha voces en su armario</descripcion>
    </personaje>
    <personaje id="P2" tipo="secundario">
      <nombre>Abuela Rosa</nombre>
      <genero>F</genero>
      <descripcion>La abuela de Daniel, la única que le cree</descripcion>
      <imagen>abuela_rosa.jpg</imagen>
    </personaje>
  </personajes>
  
  <trama>Daniel descubre que el armario de su habitación contiene una puerta a un mundo donde las pesadillas cobran vida,
   y solo su abuela parece entender lo que ocurre.</trama>
  
  <etiqueta nombre="infantil"/>
  <etiqueta nombre="suspense"/>
</cuento>

=== Castellers/XML1/05.01 Validación XML - DTD III/bosque_lunas_grises.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Sergio Pedraza Crespo
Curso: ASIR
Fecha: 3/04/2025
Ejercicio: 05.03. Validación XML - DTD III Ejercicio 1
-->
<!DOCTYPE cuento SYSTEM "cuentos.dtd">
<cuento cod="F23" titulo="El Bosque de las Lunas Grises" genero="fantasía">
  <personajes>
    <personaje id="P1" tipo="principal">
      <nombre>Liora</nombre>
      <genero>F</genero>
      <descripcion>Una joven con la capacidad de hablar con los árboles</descripcion>
      <descripcion_fisica>Cabello plateado y ojos verdes brillantes</descripcion_fisica>
    </personaje>
    <personaje id="P2" tipo="antagonista">
      <nombre>El Devorador de Sombras</nombre>
      <genero>N</genero>
      <descripcion>Una entidad que consume la luz de los sueños</descripcion>
    </personaje>
  </personajes>
  
  <trama>En un bosque donde la luna proyecta sombras grises, Liora debe recuperar la luz robada por el Devorador antes de que el bosque desaparezca para siempre.</trama>
  
  <etiqueta nombre="magia"/>
  <etiqueta nombre="bosque"/>
  <etiqueta nombre="aventura"/>
  
  <precio moneda="eur">12.50</precio>
</cuento>
